<#
    gen-dashboard-data.ps1  -  Package the JSON metrics into docs\data.js.

    The HTML dashboard (docs\dashboard.html) loads its data from docs\data.js via
    a plain <script> tag rather than fetch(), so it works both locally (file://)
    and on GitHub Pages (no CORS issues). This script reads the two JSON files
    produced by the binaries and wraps them into that data.js as two globals:

        window.QMM_METRICS = { ...simulator metrics... };
        window.QMM_BENCH   = { ...queue-benchmark metrics... };

    Usage:
      .\scripts\gen-dashboard-data.ps1 -Metrics build\metrics.json -Bench build\bench.json
#>
param(
    [string]$Metrics = (Join-Path (Split-Path -Parent $PSScriptRoot) "build\metrics.json"),
    [string]$Bench   = (Join-Path (Split-Path -Parent $PSScriptRoot) "build\bench.json"),
    [string]$Out     = (Join-Path (Split-Path -Parent $PSScriptRoot) "docs\data.js")
)

$ErrorActionPreference = "Stop"

# Read a JSON file's raw text, or "null" if it is missing (the dashboard guards
# against null so a partial run still renders what data it has).
function Read-JsonText($path) {
    if (Test-Path $path) { return (Get-Content $path -Raw) }
    Write-Warning "metrics file not found: $path (dashboard panel will show a placeholder)"
    return "null"
}

$metricsText = Read-JsonText $Metrics
$benchText   = Read-JsonText $Bench
$stamp       = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")

$content = @"
// AUTO-GENERATED by scripts\gen-dashboard-data.ps1 -- do not edit by hand.
// Regenerate with:  .\scripts\run-all.ps1   (or run-all with -Events/-Rate)
// Generated (UTC): $stamp
window.QMM_GENERATED_UTC = "$stamp";
window.QMM_METRICS = $metricsText;
window.QMM_BENCH   = $benchText;
"@

# Ensure the output directory exists, then write UTF-8 without a BOM.
$outDir = Split-Path -Parent $Out
if (-not (Test-Path $outDir)) { New-Item -ItemType Directory -Path $outDir | Out-Null }
[System.IO.File]::WriteAllText($Out, $content, (New-Object System.Text.UTF8Encoding($false)))

Write-Host "wrote dashboard data -> $Out" -ForegroundColor Green
